# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 09:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_uah', models.IntegerField(verbose_name='Salary')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 1, 10, 9, 54, 9, 768537), verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Patronymic')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('index', models.CharField(max_length=6, verbose_name='Index')),
                ('tel', models.CharField(max_length=15, unique=True, verbose_name='Phone number')),
                ('ip_number', models.CharField(max_length=12, unique=True, verbose_name='ID number')),
                ('score_number', models.CharField(max_length=14, unique=True, verbose_name='Score number')),
                ('mfo', models.CharField(max_length=6, verbose_name='MFO')),
                ('contract', models.CharField(max_length=30, unique=True, verbose_name='Contract №')),
                ('date_contract', models.DateTimeField(default=datetime.datetime(2017, 1, 10, 9, 54, 9, 768537), verbose_name='Contract Date')),
                ('service', models.CharField(max_length=500, verbose_name='Service')),
            ],
        ),
        migrations.AddField(
            model_name='salary',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zpapp.Worker'),
        ),
    ]
