# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 07:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 13, 7, 33, 59, 835120), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_contract',
            field=models.DateField(default=datetime.datetime(2017, 1, 13, 7, 33, 59, 835120), verbose_name='Contract Date'),
        ),
    ]
